package com.github.albertocavalcante.groovylsp

import kotlinx.coroutines.runBlocking
import org.eclipse.lsp4j.ClientCapabilities
import org.eclipse.lsp4j.DidOpenTextDocumentParams
import org.eclipse.lsp4j.InitializeParams
import org.eclipse.lsp4j.InitializedParams
import org.eclipse.lsp4j.TextDocumentItem
import org.eclipse.lsp4j.WorkspaceFolder
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import kotlin.test.assertTrue

class JenkinsParsingTest {

    private lateinit var server: GroovyLanguageServer
    private lateinit var mockClient: SynchronizingTestLanguageClient

    @BeforeEach
    fun setup() {
        server = GroovyLanguageServer()
        mockClient = SynchronizingTestLanguageClient()
        server.connect(mockClient)
    }

    @Test
    fun `test pipeline block resolves successfully with stubs`() = runBlocking {
        // Initialize server
        val initParams = InitializeParams().apply {
            workspaceFolders = listOf(WorkspaceFolder("file:///test/project", "project"))
            capabilities = ClientCapabilities()
        }
        server.initialize(initParams).get()
        server.initialized(InitializedParams())

        // Open Jenkinsfile
        // We use a complex Declarative Pipeline to trigger unknown identifier errors
        // specifically 'pipeline', 'agent', 'stages' which are missing from the default classpath
        val params = DidOpenTextDocumentParams().apply {
            textDocument = TextDocumentItem().apply {
                uri = "file:///test/project/Jenkinsfile"
                languageId = "groovy"
                version = 1
                text = """
                    pipeline {
                        agent any
                        stages {
                            stage('Example') {
                                steps {
                                    sh 'echo Hello'
                                }
                            }
                        }
                    }
                """.trimIndent()
            }
        }

        server.textDocumentService.didOpen(params)

        // Wait for diagnostics
        // We expect diagnostics because 'pipeline' and other DSL elements are not defined
        // in the standard Groovy environment or jenkins-core alone.
        val diagnostics = mockClient.awaitDiagnosticsForUri("file:///test/project/Jenkinsfile", timeoutMs = 10000)

        // With stubs generated by JenkinsContext, we expect NO errors.
        if (diagnostics.diagnostics.isNotEmpty()) {
            val errors = diagnostics.diagnostics.joinToString("\n") { "${it.message} at line ${it.range.start.line}" }
            throw AssertionError("Expected successful compilation but got errors:\n$errors")
        }
        assertTrue(
            diagnostics.diagnostics.isEmpty(),
            "Should have no compilation errors for valid Declarative Pipeline",
        )
    }
}
