load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "sarif",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//diagnostics/api",
        "@maven//:org_eclipse_lsp4j_org_eclipse_lsp4j",
        "@maven//:org_eclipse_lsp4j_org_eclipse_lsp4j_jsonrpc",
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
        "@maven//:org_jetbrains_kotlinx_kotlinx_serialization_json",
    ],
)

kt_test(
    name = "sarif_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    deps = [
        ":sarif",
        "@maven//:org_junit_platform_junit_platform_launcher",
    ],
)
