load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "ast-model",
    srcs = glob([
        "src/commonMain/kotlin/**/*.kt",
        "src/jvmMain/kotlin/**/*.kt",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//parser/core",
        "//parser/native",
        "//parser/rewrite",
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
        "@maven//:org_jetbrains_kotlinx_kotlinx_serialization_json",
    ],
)

kt_test(
    name = "ast-model_test",
    srcs = glob([
        "src/commonTest/kotlin/**/*.kt",
        "src/jvmTest/kotlin/**/*.kt",
    ]),
    deps = [
        ":ast-model",
        "@maven//:org_jetbrains_kotlin_kotlin_test",
        "@maven//:org_junit_platform_junit_platform_launcher",
    ],
)
