load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "rewrite",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//parser/api",
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
        "@maven//:org_openrewrite_rewrite_groovy",
    ],
)

kt_test(
    name = "rewrite_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    deps = [
        ":rewrite",
        "@maven//:org_junit_platform_junit_platform_launcher",
    ],
)
