load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "core",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//dsl/dsld",
        "@maven//:io_arrow_kt_arrow_core_jvm",
        "@maven//:org_apache_groovy_groovy",
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
    ],
)

kt_test(
    name = "core_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    associates = [":core"],
    test_packages = ["com.github.albertocavalcante.gvy"],
    deps = [
        "@maven//:io_arrow_kt_arrow_core_jvm",
        "@maven//:org_apache_groovy_groovy",
    ],
)
