load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "openrewrite",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//semantics/core",
        "@maven//:io_arrow_kt_arrow_core",
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
        "@maven//:org_openrewrite_rewrite_groovy",
    ],
)

kt_test(
    name = "openrewrite_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    deps = [
        ":openrewrite",
        "@maven//:ch_qos_logback_logback_classic",
        "@maven//:org_jetbrains_kotlin_kotlin_test",
        "@maven//:org_junit_platform_junit_platform_launcher",
    ],
)
