load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "codenarc",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//diagnostics/api",
        "//parser/native",
        "@maven//:org_apache_groovy_groovy",
        "@maven//:org_apache_groovy_groovy_json",
        "@maven//:org_codenarc_CodeNarc",
        "@maven//:org_eclipse_lsp4j_org_eclipse_lsp4j",
        "@maven//:org_gmetrics_GMetrics",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
        "@maven//:org_slf4j_slf4j_api",
    ],
)

kt_test(
    name = "codenarc_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    test_packages = ["com.github.albertocavalcante.diagnostics"],
    associates = [":codenarc"],
    deps = [
        "@maven//:io_mockk_mockk_jvm",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_test",
    ],
)
