load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "api",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
    ],
)

kt_test(
    name = "api_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    deps = [
        ":api",
        "@maven//:org_jetbrains_kotlin_kotlin_test",
    ],
)
