load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "core",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//parser/api",
        "@maven//:org_apache_groovy_groovy",
        "@maven//:org_slf4j_slf4j_api",
    ],
)

kt_test(
    name = "core_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    deps = [
        ":core",
    ],
)
