package com.github.albertocavalcante.groovyparser.spi

import com.github.albertocavalcante.groovyparser.ast.Node
import com.github.albertocavalcante.groovyparser.ast.body.FieldDeclaration
import com.github.albertocavalcante.groovyparser.ast.body.MethodDeclaration

/**
 * Service Provider Interface for AST transform awareness.
 *
 * Implementations of this interface can provide information about members
 * generated by AST transformations like @ToString, @EqualsAndHashCode, etc.
 *
 * This allows the parser library to understand code that uses compile-time
 * transformations without actually executing them.
 *
 * Example usage:
 * ```kotlin
 * class ToStringTransformProvider : TransformProvider {
 *     override fun getGeneratedMethods(annotationName: String, node: Node): List<MethodDeclaration> {
 *         if (annotationName == "groovy.transform.ToString") {
 *             return listOf(MethodDeclaration("toString", "String"))
 *         }
 *         return emptyList()
 *     }
 * }
 * ```
 */
interface TransformProvider {

    /**
     * Returns methods that would be generated by the given annotation.
     *
     * @param annotationName the fully qualified name of the annotation
     * @param node the annotated node (typically a ClassDeclaration)
     * @return list of methods that would be generated
     */
    fun getGeneratedMethods(annotationName: String, node: Node): List<MethodDeclaration>

    /**
     * Returns fields that would be generated by the given annotation.
     *
     * @param annotationName the fully qualified name of the annotation
     * @param node the annotated node
     * @return list of fields that would be generated
     */
    fun getGeneratedFields(annotationName: String, node: Node): List<FieldDeclaration>

    /**
     * Returns true if this provider handles the given annotation.
     *
     * @param annotationName the fully qualified name of the annotation
     * @return true if this provider can generate members for this annotation
     */
    fun handles(annotationName: String): Boolean
}
