load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "markdown",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
    ],
)

kt_test(
    name = "markdown_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    deps = [
        ":markdown",
        "@maven//:org_jetbrains_kotlin_kotlin_test",
        "@maven//:org_junit_platform_junit_platform_launcher",
    ],
)
