load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "results",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//reports/api",
        "@maven//:io_github_oshai_kotlin_logging_jvm",
    ],
)

kt_test(
    name = "results_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    test_packages = ["com.github.albertocavalcante.reports.results"],
    associates = [":results"],
    resources = glob(["src/test/resources/**/*"]),
    deps = [
        "@maven//:io_mockk_mockk_jvm",
    ],
)
