load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

# Export proto file for Wire codegen
exports_files(["scip.proto"])

proto_library(
    name = "proto_proto",
    srcs = ["scip.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "proto_go_proto",
    importpath = "github.com/sourcegraph/scip/bindings/go/scip/",
    proto = ":proto_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "scip",
    embed = [":proto_go_proto"],
    importpath = "github.com/sourcegraph/scip/bindings/go/scip/",
    visibility = ["//visibility:public"],
)
