load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "gdsl",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:io_github_oshai_kotlin_logging_jvm",
        "@maven//:org_apache_groovy_groovy",
        "@maven//:org_slf4j_slf4j_api",
    ],
)

kt_test(
    name = "groovy-gdsl_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    test_packages = ["com.github.albertocavalcante.groovygdsl"],
    associates = [":groovy-gdsl"],
    deps = [
        "@maven//:io_mockk_mockk_jvm",
        "@maven//:org_apache_groovy_groovy",
    ],
)
