load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "native",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//dsl/dsld",
        "//parser/core",
        "//semantics/core",
        "@maven//:org_apache_groovy_groovy",
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
    ],
)

kt_test(
    name = "native_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    associates = [":native"],
    deps = [
        "//parser/api",
        "//parser/native",
        "@maven//:org_junit_platform_junit_platform_launcher",
    ],
)
