load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "native",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//common",
        "//parser/core",
        "//semantics/core",
        "@maven//:io_arrow_kt_arrow_core_jvm",
        "@maven//:org_apache_groovy_groovy",
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
    ],
)

kt_test(
    name = "native_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    associates = [":native"],
    test_packages = ["com.github.albertocavalcante.gvy"],
    deps = [
        "//parser/core",
        "//parser/native",
        "//semantics/core",
        "@maven//:org_apache_groovy_groovy",
    ],
)
