load("//tools/build_defs:kotlin.bzl", "kt_library", "kt_test")

kt_library(
    name = "spock",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//dsl/dsld",
        "//parser/native",
        "@maven//:org_slf4j_slf4j_api",
    ],
)

kt_test(
    name = "groovy-spock_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    test_packages = ["com.github.albertocavalcante.groovyspock"],
    associates = [":groovy-spock"],
    deps = [
        "//parser/native",
        "@maven//:org_apache_groovy_groovy",
        "@maven//:org_spockframework_spock_core",
    ],
)
